hubaseURL = 'https://asdasdasd.github.io/'
languageCode = 'en-us'
theme = "hugo-eureka"

[params]
title = "asdasdasd"
author = "megváltozott"
description = "tudatfolyam"
profilePicture = "images/c.JPG"
mainSections = ["blog"]
